% File to test the use of PlotBrainGraph.
%
% See also PlotBrainGraph, ListElement.

% Author: Mite Mijalkov, Ehsan Kakaei & Giovanni Volpe
% Date: 2016/01/01

close all
clear all
clc

%% Create BrainAtlas from BrainRegion list

br1 = BrainRegion(BrainRegion.LABEL,'1', ...
    BrainRegion.NAME,'Brain Region 1', ...
    BrainRegion.X,1, ...
    BrainRegion.Y,1, ...
    BrainRegion.Z,1, ...
    BrainRegion.HS,BrainRegion.HS_RIGHT, ...
    BrainRegion.NOTES,'notes ...');
br2 = BrainRegion(BrainRegion.LABEL,'2', ...
    BrainRegion.NAME,'Brain Region 2', ...
    BrainRegion.X,2, ...
    BrainRegion.Y,-2, ...
    BrainRegion.Z,2, ...
    BrainRegion.HS,BrainRegion.HS_RIGHT, ...
    BrainRegion.NOTES,'notes ...');
br3 = BrainRegion(BrainRegion.LABEL,'3', ...
    BrainRegion.NAME,'Brain Region 3', ...
    BrainRegion.X,3, ...
    BrainRegion.Y,3, ...
    BrainRegion.Z,-3, ...
    BrainRegion.HS,BrainRegion.HS_RIGHT, ...
    BrainRegion.NOTES,'notes ...');
br4 = BrainRegion(BrainRegion.LABEL,'4', ...
    BrainRegion.NAME,'Brain Region 4', ...
    BrainRegion.X,-4, ...
    BrainRegion.Y,4, ...
    BrainRegion.Z,4, ...
    BrainRegion.HS,BrainRegion.HS_RIGHT, ...
    BrainRegion.NOTES,'notes ...');
br5 = BrainRegion(BrainRegion.LABEL,'5', ...
    BrainRegion.NAME,'Brain Region 5', ...
    BrainRegion.X,-5, ...
    BrainRegion.Y,-5, ...
    BrainRegion.Z,5, ...
    BrainRegion.HS,BrainRegion.HS_LEFT, ...
    BrainRegion.NOTES,'notes ...');

brs{1} = br1;
brs{2} = br2;
brs{3} = br3;
brs{4} = br4;
brs{5} = br5;

atlas = BrainAtlas(brs,BrainAtlas.NAME,'Atlas');

%% PlotBrainGraph
bg = PlotBrainGraph(atlas)
h = bg.set_axes()
bg.axis_equal()
bg.view(PlotBrainSurf.VIEW_3D)
bg.hold_on()
bg.br_syms()

%% Lines
bg.link_lins(4,2,'LineWidth',1,'Color',[0 0 1])
bg.link_lins_settings([],[],...
    'FigPosition',[.10 .20 .30 .30], ...
    'FigColor',GUI.BKGCOLOR, ...
    'FigName','PlotBrainGraph - Lines' ...
    )

%% Arrows
bg.link_arrs(1,2,'StemWidth',.5,'Color',[1 0 0])
bg.link_arrs_settings([],[],...
    'FigPosition',[.20 .30 .30 .30], ...
    'FigColor',GUI.BKGCOLOR, ...
    'FigName','PlotBrainGraph - Arrows' ...
    )

%% Cylinders
bg.link_cyls(3,5,'R',.15,'Color',[.7 .7 .7])
bg.link_cyls_settings([],[],...
    'FigPosition',[.30 .40 .30 .30], ...
    'FigColor',GUI.BKGCOLOR, ...
    'FigName','PlotBrainGraph - Cylinders' ...
    )

h = bg.get_axes()