% File to test the use of PlotBrainAtlas.
%
% See also PlotBrainAtlas, ListElement.

% Author: Mite Mijalkov, Ehsan Kakaei & Giovanni Volpe
% Date: 2016/01/01

close all
clear all
clc

%% Create BrainAtlas from BrainRegion list

br1 = BrainRegion( ...
    BrainRegion.LABEL,'BR 1', ...
    BrainRegion.NAME,'Region 1', ...
    BrainRegion.X,11, ...
    BrainRegion.Y,12, ...
    BrainRegion.Z,13, ...
    BrainRegion.HS,BrainRegion.HS_LEFT, ...
    BrainRegion.NOTES,'Brain Region Notes' ...
    );

br2 = BrainRegion( ...
    BrainRegion.LABEL,'BR 2', ...
    BrainRegion.NAME,'Region 2', ...
    BrainRegion.X,21, ...
    BrainRegion.Y,22, ...
    BrainRegion.Z,23, ...
    BrainRegion.HS,BrainRegion.HS_LEFT, ...
    BrainRegion.NOTES,'Brain Region Notes' ...
    );

br3 = BrainRegion( ...
    BrainRegion.LABEL,'BR 3', ...
    BrainRegion.NAME,'Region 3', ...
    BrainRegion.X,31, ...
    BrainRegion.Y,32, ...
    BrainRegion.Z,33, ...
    BrainRegion.HS,BrainRegion.HS_RIGHT, ...
    BrainRegion.NOTES,'Brain Region Notes' ...
    );

br4 = BrainRegion( ...
    BrainRegion.LABEL,'BR 4', ...
    BrainRegion.NAME,'Region 4', ...
    BrainRegion.X,41, ...
    BrainRegion.Y,42, ...
    BrainRegion.Z,43, ...
    BrainRegion.HS,BrainRegion.HS_RIGHT, ...
    BrainRegion.NOTES,'Brain Region Notes' ...
    );

br5 = BrainRegion( ...
    BrainRegion.LABEL,'BR 5', ...
    BrainRegion.NAME,'Region 5', ...
    BrainRegion.X,51, ...
    BrainRegion.Y,52, ...
    BrainRegion.Z,53, ...
    BrainRegion.HS,BrainRegion.HS_RIGHT, ...
    BrainRegion.NOTES,'Brain Region Notes' ...
    );

brs{1} = br1;
brs{2} = br2;
brs{3} = br3;
brs{4} = br4;
brs{5} = br5;

atlas1 = BrainAtlas(brs);

%% PlotBrainAtlas

ba = PlotBrainAtlas(atlas1)

h = ba.set_axes()
ba.hold_on()
ba.view(PlotBrainAtlas.VIEW_3D)

%% Symbols

ba.br_syms()
ba.br_syms_on()

ba.br_syms_settings([], ...
    'FigPosition',[.1 .2 .4 .4], ...
    'FigColor',GUI.BKGCOLOR, ...
    'FigTitle','PlotBrainSurf - Symbols' ...
    )

%% Spheres

ba.br_sphs()
ba.br_sphs_on()

ba.br_sphs_settings([], ...
    'FigPosition',[.2 .3 .4 .4], ...
    'FigColor',GUI.BKGCOLOR, ...
    'FigTitle','PlotBrainSurf - Spheres' ...
    )

%% Labels

ba.br_labs()
ba.br_labs_on()

ba.br_labs_settings([], ...
    'FigPosition',[.3 .4 .4 .4], ...
    'FigColor',GUI.BKGCOLOR, ...
    'FigTitle','PlotBrainSurf - Labels' ...
    )
