% File to test the use of fMRICohort.
%
% See also fMRICohort.

% Author: Mite Mijalkov, Ehsan Kakaei & Giovanni Volpe
% Date: 2016/01/01

close all
clear all
clc

%% Create BrainAtlas from BrainRegion list

br1 = BrainRegion(BrainRegion.LABEL,'REG. 1', ...
    BrainRegion.NAME,'Brain Region 1', ...
    BrainRegion.X,1, ...
    BrainRegion.Y,1, ...
    BrainRegion.Z,1, ...
    BrainRegion.HS,BrainRegion.HS_LEFT, ...
    BrainRegion.NOTES,'notes1 ...');

br2 = BrainRegion(BrainRegion.LABEL,'REG. 2', ...
    BrainRegion.NAME,'Brain Region 2', ...
    BrainRegion.X,2, ...
    BrainRegion.Y,-2, ...
    BrainRegion.Z,2, ...
    BrainRegion.HS,BrainRegion.HS_RIGHT, ...
    BrainRegion.NOTES,'notes2 ...');

br3 = BrainRegion(BrainRegion.LABEL,'REG. 3', ...
    BrainRegion.NAME,'Brain Region 3', ...
    BrainRegion.X,3, ...
    BrainRegion.Y,3, ...
    BrainRegion.Z,-3, ...
    BrainRegion.HS,BrainRegion.HS_LEFT, ...
    BrainRegion.NOTES,'notes3 ...');

br4 = BrainRegion(BrainRegion.LABEL,'REG. 4', ...
    BrainRegion.NAME,'Brain Region 4', ...
    BrainRegion.X,-4, ...
    BrainRegion.Y,4, ...
    BrainRegion.Z,4, ...
    BrainRegion.HS,BrainRegion.HS_RIGHT, ...
    BrainRegion.NOTES,'notes4 ...');

br5 = BrainRegion(BrainRegion.LABEL,'REG. 5', ...
    BrainRegion.NAME,'Brain Region 5', ...
    BrainRegion.X,-5, ...
    BrainRegion.Y,-5, ...
    BrainRegion.Z,5, ...
    BrainRegion.HS,BrainRegion.HS_LEFT, ...
    BrainRegion.NOTES,'notes5 ...');

brs = {br1 br2 br3 br4 br5};
atlas = BrainAtlas(brs,BrainAtlas.NAME,'Atlas1');

%% creating subects, groups and cohort

sub1 = fMRISubject( ...
    fMRISubject.CODE,'SUB1', ...
    fMRISubject.AGE,75, ...
    fMRISubject.GENDER,fMRISubject.GENDER_FEMALE, ...
    fMRISubject.DATA,10*rand(length(atlas)), ...
    fMRISubject.NOTES,'none');
sub2 = fMRISubject( ...
    fMRISubject.CODE,'SUB1', ...
    fMRISubject.AGE,75, ...
    fMRISubject.GENDER,fMRISubject.GENDER_FEMALE, ...
    fMRISubject.DATA,10*rand(length(atlas)), ...
    fMRISubject.NOTES,'none');
sub3 = fMRISubject( ...
    fMRISubject.CODE,'SUB1', ...
    fMRISubject.AGE,75, ...
    fMRISubject.GENDER,fMRISubject.GENDER_FEMALE, ...
    fMRISubject.DATA,10*rand(length(atlas)), ...
    fMRISubject.NOTES,'none');
sub4 = fMRISubject(atlas, ...
    fMRISubject.CODE,'SUB1', ...
    fMRISubject.AGE,75, ...
    fMRISubject.GENDER,fMRISubject.GENDER_FEMALE, ...
    fMRISubject.DATA,10*rand(length(atlas)), ...
    fMRISubject.NOTES,'none');

subjects = {sub1 sub2 sub3 sub4};

cohort = fMRICohort(atlas,subjects,fMRICohort.NAME,'cohort 1',fMRICohort.T,10);

g1 = Group(Group.NAME,'gr1',Group.DATA,[1 1 0 0],Group.NOTES,'notes gr 1');
g2 = Group(Group.NAME,'gr2',Group.DATA,[0 0 1 1],Group.NOTES,'notes gr 2');
cohort.addgroup(g1)  % add group g1 to cohort
cohort.addgroup(g2)  % add group g2 to cohort

%% get subject data

subjects = cohort.getSubjectData(1);

%% toXML, fromXML   

% save cohort to XML file
Document = com.mathworks.xml.XMLUtils.createDocument('xml');
RootNode = Document.getDocumentElement;
Node = cohort.toXML(Document,RootNode);
cohort_xml = xmlwrite(Document)

% load cohort from XML file
cohort_loadxml = fMRICohort(atlas);
cohort_loadxml.fromXML(Node)
cohort.disp()