% File to test the use of EEGSubject.
%
% See also EEGSubject.

% Author: Mite Mijalkov, Ehsan Kakaei & Giovanni Volpe
% Date: 2016/01/01

close all
clear all
clc

%% Create BrainAtlas from BrainRegion list

br1 = BrainRegion(BrainRegion.LABEL,'REG. 1', ...
    BrainRegion.NAME,'Brain Region 1', ...
    BrainRegion.X,1, ...
    BrainRegion.Y,1, ...
    BrainRegion.Z,1, ...
    BrainRegion.HS,BrainRegion.HS_LEFT, ...
    BrainRegion.NOTES,'notes1 ...');

br2 = BrainRegion(BrainRegion.LABEL,'REG. 2', ...
    BrainRegion.NAME,'Brain Region 2', ...
    BrainRegion.X,2, ...
    BrainRegion.Y,-2, ...
    BrainRegion.Z,2, ...
    BrainRegion.HS,BrainRegion.HS_RIGHT, ...
    BrainRegion.NOTES,'notes2 ...');

br3 = BrainRegion(BrainRegion.LABEL,'REG. 3', ...
    BrainRegion.NAME,'Brain Region 3', ...
    BrainRegion.X,3, ...
    BrainRegion.Y,3, ...
    BrainRegion.Z,-3, ...
    BrainRegion.HS,BrainRegion.HS_LEFT, ...
    BrainRegion.NOTES,'notes3 ...');

br4 = BrainRegion(BrainRegion.LABEL,'REG. 4', ...
    BrainRegion.NAME,'Brain Region 4', ...
    BrainRegion.X,-4, ...
    BrainRegion.Y,4, ...
    BrainRegion.Z,4, ...
    BrainRegion.HS,BrainRegion.HS_RIGHT, ...
    BrainRegion.NOTES,'notes4 ...');

brs = {br1 br2 br3 br4};
atlas = BrainAtlas(brs,BrainAtlas.NAME,'Sample Atlas');

%% Create a MRI Subject

sub = EEGSubject( ...
    EEGSubject.CODE,'SUB1', ...
    EEGSubject.AGE,75, ...
    EEGSubject.GENDER,EEGSubject.GENDER_FEMALE, ...
    EEGSubject.DATA,10*rand(length(atlas)), ...
    EEGSubject.NOTES,'none');

%% get subject properties

TAGS = sub.getTags()  % get tags
FORMATS = sub.getFormats()  % get formats
DEFAULTS = sub.getDefaults()  % get defaults
OPTIONS = sub.getOptions(MRISubject.GENDER)  % get options